export const GET_CATEGORIES   = 'GET_CATEGORIES';
export const GET_POSTS = 'GET_POSTS';
export const GET_CATEGORY_POSTS = 'GET_CATEGORY_POSTS';
export const GET_POST = 'GET_POST';

export const START_LOADING_COMMENTS = 'START_LOADING_COMMENTS';
export const SUCCESS_LOADING_COMMENTS = 'SUCCESS_LOADING_COMMENTS';
export const ERROR_LOADING_COMMENTS = 'ERROR_LOADING_COMMENTS';